### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by retronbv** [3kh0/3kh0-forms#1]
![2EBAF554-4980-467B-AD2E-BACE44E54BAB](https://user-images.githubusercontent.com/49005044/152188475-f454e160-098a-454c-b61e-9357e4030b66.jpeg)

**Comment by 3kh0** [comment]
How did you get here so fast? I switched to netify because they have a forms feature, it will come soon lol

**Comment by xLunarr** [comment]
> How did you get here so fast? I switched to netify because they have a forms feature, it will come soon lol

is it here now

**Comment by xLunarr** [comment]
@3kh0

**Comment by xLunarr** [comment]
@3kh0
